version: '3.11'

services:

  db:
    image: postgres:14-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}

  redis:
    image: redis:latest
    container_name: redis


  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq

  celery:
    restart: always
    build:
      context: ./
    command: celery -A online_store worker -l INFO
    volumes:
      - ./:/usr/src/app/
    container_name: celery
    depends_on:
      - db
      - redis
      - rabbitmq
      - web

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    container_name: online_store
    volumes:
      - ./:/usr/src/app/
      - /var/www/back/static/:/usr/src/app/static/
      - /var/www/back/media/:/usr/src/app/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - rabbitmq
      - celery

volumes:
  postgres_data: